# .github/workflows/check_archive.yml
name: Notify Upon Failure

on:
  workflow_run:
    workflows: ["Link Checker"]
    types:
      - completed


jobs:
  check-archive:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for errors
      id: check_errors
      run: |
        if grep -q '❌' Archives.md; then
          echo "Errors found in Archives.md"
          exit 1
        else
          echo "No errors found in Archives.md"
        fi

    - name: Send notifications
      if: failure()
      run: |
        ALERT_LIST=$(cat .github/alert_list.txt)
        for USER in $ALERT_LIST; do
          curl -X POST -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"❌ Errors found in Archives.md","body":"@'${USER}' ❌ Errors were found in the latest Archive.md check.","assignees":["${USER}"]}'
        done
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
